### ISSUE TITLE
Version Pinning with REST for new metric

### ISSUE THREAD

**Issue by sdlott** [461-Team-14/Project-2#6]

**Comment by sdlott** [comment]
New metric, The fraction of dependencies that are pinned to at least a specific major+minor version, e.g., version 2.3.X of a package. (If there are zero dependencies, they should receive a 1.0 rating. If there are two dependencies, one pinned to this degree, then they should receive a ½ = 0.5 rating).

**Comment by Ham-png** [comment]
Done!
